[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
prost = "0.13"
jni = "0.21.1"
num-complex = "0.4"
aes = "0.9.2"
ctr = "0.10.1"
rustfft = "6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.10.2"

[build-dependencies]
prost-build = "0.13"
