//! Thin wrapper around prost-generated Meshtastic protobuf types.
//!
//! REQUIRES the real .proto files from github.com/meshtastic/protobufs,
//! compiled via prost-build in build.rs — do NOT hand-write the message
//! structs. Field numbers must match the wire format exactly or packets
//! silently fail to parse (or worse, misparse into garbage that looks like
//! a different valid message).
//!
//! build.rs sketch:
//!   fn main() {
//!       prost_build::compile_protos(
//!           &["vendor/protobufs/meshtastic/mesh.proto", /* + portnums.proto,
//!             channel.proto, etc. as needed */],
//!           &["vendor/protobufs/"],
//!       ).unwrap();
//!   }
//!   (vendor/protobufs/ = git submodule of meshtastic/protobufs)
//!
//! FIELD NAMES BELOW (packet.from, packet.id, packet.channel,
//! PayloadVariant::Encrypted/Decoded) reflect the generally-documented
//! public shape of MeshPacket — matches what's referenced consistently
//! across meshtastic.org docs and community sources, but I have not
//! personally inspected the current .proto file byte-for-byte. Once you
//! generate the real code, diff these field accesses against it — a
//! renamed field is a compile error (easy), a field with the same name but
//! different meaning would not be (worth a quick sanity check).

use crate::crypto::{self, ChannelKey};

// Generated by prost-build — see build.rs sketch above.
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/meshtastic.rs"));
}

use prost::Message;
use proto::{mesh_packet::PayloadVariant, Data, MeshPacket};

#[derive(Debug)]
pub enum PacketError {
    Protobuf(prost::DecodeError),
    NoMatchingChannelKey,
    PacketTooShort,
}

impl From<prost::DecodeError> for PacketError {
    fn from(e: prost::DecodeError) -> Self {
        PacketError::Protobuf(e)
    }
}

/// One channel this app knows about, for trying against incoming packets.
pub struct KnownChannel {
    pub name: String,
    pub key: ChannelKey,
}

/// Parses raw LoRa-PHY-decoded bytes into a MeshPacket. If the payload is
/// the Encrypted variant, tries each known channel (matched by
/// channel_hash — see crypto.rs) and returns a packet with the Decoded
/// variant once one successfully decrypts + parses as a valid Data message.
pub fn decode_mesh_packet(
    bytes: &[u8],
    known_channels: &[KnownChannel],
) -> Result<MeshPacket, PacketError> {
    if bytes.len() < 16 {
        return Err(PacketError::PacketTooShort);
    }

    let to = u32::from_le_bytes(bytes[0..4].try_into().unwrap());
    let from = u32::from_le_bytes(bytes[4..8].try_into().unwrap());
    let id = u32::from_le_bytes(bytes[8..12].try_into().unwrap());

    let flags = bytes[12];
    let hop_limit = (flags & 0x07) as u32;
    let want_ack = (flags & 0x08) != 0;
    let via_mqtt = (flags & 0x10) != 0;
    let hop_start = ((flags >> 5) & 0x07) as u32;

    let target_hash = bytes[13];
    let next_hop = bytes[14] as u32;
    let relay_node = bytes[15] as u32;
    let ciphertext = &bytes[16..];

    for kc in known_channels {
        let psk_bytes: &[u8] = match &kc.key {
            ChannelKey::Aes256(k) => k,
            ChannelKey::Aes128(k) => k,
        };
        if crypto::channel_hash(&kc.name, psk_bytes) != target_hash {
            continue;
        }
        let mut plaintext = ciphertext.to_vec();
        crypto::crypt_payload(&kc.key, from, id, &mut plaintext);
        if let Ok(data) = Data::decode(plaintext.as_slice()) {
            let mut packet = MeshPacket::default();
            packet.to = to;
            packet.from = from;
            packet.id = id;
            packet.hop_limit = hop_limit;
            packet.hop_start = hop_start;
            packet.want_ack = want_ack;
            packet.via_mqtt = via_mqtt;
            packet.channel = target_hash as u32;
            packet.next_hop = next_hop;
            packet.relay_node = relay_node;
            packet.payload_variant = Some(PayloadVariant::Decoded(data));
            return Ok(packet);
        }
    }

    Err(PacketError::NoMatchingChannelKey)
}

/// Encodes a MeshPacket back to wire bytes, encrypting the Decoded payload
/// against the given channel first.
pub fn encode_mesh_packet(packet: MeshPacket, channel_name: &str, key: &ChannelKey) -> Vec<u8> {
    let mut out = vec![0u8; 16];
    out[0..4].copy_from_slice(&packet.to.to_le_bytes());
    out[4..8].copy_from_slice(&packet.from.to_le_bytes());
    out[8..12].copy_from_slice(&packet.id.to_le_bytes());

    let mut flags = (packet.hop_limit & 0x07) as u8;
    if packet.want_ack {
        flags |= 0x08;
    }
    if packet.via_mqtt {
        flags |= 0x10;
    }
    flags |= ((packet.hop_start & 0x07) as u8) << 5;
    out[12] = flags;

    let psk_bytes: &[u8] = match key {
        ChannelKey::Aes256(k) => k,
        ChannelKey::Aes128(k) => k,
    };
    out[13] = crypto::channel_hash(channel_name, psk_bytes);

    out[14] = packet.next_hop as u8;
    out[15] = packet.relay_node as u8;

    if let Some(PayloadVariant::Decoded(data)) = &packet.payload_variant {
        let mut plaintext = Vec::new();
        data.encode(&mut plaintext)
            .expect("Data encode should not fail");
        crypto::crypt_payload(key, packet.from, packet.id, &mut plaintext);
        out.extend_from_slice(&plaintext);
    } else if let Some(PayloadVariant::Encrypted(ciphertext)) = &packet.payload_variant {
        out.extend_from_slice(ciphertext);
    }

    out
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::resolve_psk;

    #[test]
    fn test_encode_decode_mesh_packet() {
        let mut data = Data::default();
        data.portnum = 1;
        data.payload = b"Hello".to_vec();

        let mut packet = MeshPacket::default();
        packet.to = 0xFFFFFFFF;
        packet.from = 0x12345678;
        packet.id = 0x87654321;
        packet.hop_limit = 3;
        packet.hop_start = 3;
        packet.want_ack = true;
        packet.via_mqtt = true;
        packet.next_hop = 42;
        packet.relay_node = 43;
        packet.payload_variant = Some(PayloadVariant::Decoded(data));

        let key = resolve_psk(&[1]).unwrap(); // Default key
        let encoded = encode_mesh_packet(packet, "LongFast", &key);

        // Assert header length is minimum 16
        assert!(encoded.len() >= 16);

        // Assert header contents
        assert_eq!(encoded[0..4], 0xFFFFFFFFu32.to_le_bytes());
        assert_eq!(encoded[4..8], 0x12345678u32.to_le_bytes());
        assert_eq!(encoded[8..12], 0x87654321u32.to_le_bytes());

        // Expected flags for hop_limit=3, hop_start=3, want_ack=true, via_mqtt=true
        let expected_flags = 3 | 0x08 | 0x10 | (3 << 5);
        assert_eq!(encoded[12], expected_flags);

        let known_channels = vec![KnownChannel {
            name: "LongFast".to_string(),
            key: resolve_psk(&[1]).unwrap(),
        }];

        let decoded = decode_mesh_packet(&encoded, &known_channels).expect("decode failed");

        assert_eq!(decoded.to, 0xFFFFFFFF);
        assert_eq!(decoded.from, 0x12345678);
        assert_eq!(decoded.id, 0x87654321);
        assert_eq!(decoded.hop_limit, 3);
        assert_eq!(decoded.hop_start, 3);
        assert_eq!(decoded.want_ack, true);
        assert_eq!(decoded.via_mqtt, true);
        assert_eq!(decoded.next_hop, 42);
        assert_eq!(decoded.relay_node, 43);

        if let Some(PayloadVariant::Decoded(d)) = decoded.payload_variant {
            assert_eq!(d.portnum, 1);
            assert_eq!(d.payload, b"Hello");
        } else {
            panic!("Expected Decoded payload variant");
        }
    }
}
