//! Thin wrapper around prost-generated Meshtastic protobuf types.
//!
//! REQUIRES the real .proto files from github.com/meshtastic/protobufs,
//! compiled via prost-build in build.rs — do NOT hand-write the message
//! structs. Field numbers must match the wire format exactly or packets
//! silently fail to parse (or worse, misparse into garbage that looks like
//! a different valid message).
//!
//! build.rs sketch:
//!   fn main() {
//!       prost_build::compile_protos(
//!           &["vendor/protobufs/meshtastic/mesh.proto", /* + portnums.proto,
//!             channel.proto, etc. as needed */],
//!           &["vendor/protobufs/"],
//!       ).unwrap();
//!   }
//!   (vendor/protobufs/ = git submodule of meshtastic/protobufs)
//!
//! FIELD NAMES BELOW (packet.from, packet.id, packet.channel,
//! PayloadVariant::Encrypted/Decoded) reflect the generally-documented
//! public shape of MeshPacket — matches what's referenced consistently
//! across meshtastic.org docs and community sources, but I have not
//! personally inspected the current .proto file byte-for-byte. Once you
//! generate the real code, diff these field accesses against it — a
//! renamed field is a compile error (easy), a field with the same name but
//! different meaning would not be (worth a quick sanity check).

use crate::crypto::{self, ChannelKey};

// Generated by prost-build — see build.rs sketch above.
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/meshtastic.rs"));
}

use proto::{mesh_packet::PayloadVariant, Data, MeshPacket};
use prost::Message;

#[derive(Debug)]
pub enum PacketError {
    Protobuf(prost::DecodeError),
    NoMatchingChannelKey,
}

impl From<prost::DecodeError> for PacketError {
    fn from(e: prost::DecodeError) -> Self {
        PacketError::Protobuf(e)
    }
}

/// One channel this app knows about, for trying against incoming packets.
pub struct KnownChannel {
    pub name: String,
    pub key: ChannelKey,
}

/// Parses raw LoRa-PHY-decoded bytes into a MeshPacket. If the payload is
/// the Encrypted variant, tries each known channel (matched by
/// channel_hash — see crypto.rs) and returns a packet with the Decoded
/// variant once one successfully decrypts + parses as a valid Data message.
pub fn decode_mesh_packet(
    bytes: &[u8],
    known_channels: &[KnownChannel],
) -> Result<MeshPacket, PacketError> {
    let mut packet = MeshPacket::decode(bytes)?;

    if let Some(PayloadVariant::Encrypted(ciphertext)) = &packet.payload_variant {
        let target_hash = packet.channel as u8;
        for kc in known_channels {
            let psk_bytes: &[u8] = match &kc.key {
                ChannelKey::Aes256(k) => k,
                ChannelKey::Aes128(k) => k,
            };
            if crypto::channel_hash(&kc.name, psk_bytes) != target_hash {
                continue;
            }
            let mut plaintext = ciphertext.clone();
            crypto::crypt_payload(&kc.key, packet.from, packet.id, &mut plaintext);
            if let Ok(data) = Data::decode(plaintext.as_slice()) {
                packet.payload_variant = Some(PayloadVariant::Decoded(data));
                return Ok(packet);
            }
        }
        return Err(PacketError::NoMatchingChannelKey);
    }

    Ok(packet) // already cleartext, or no payload
}

/// Encodes a MeshPacket back to wire bytes, encrypting the Decoded payload
/// against the given channel first.
pub fn encode_mesh_packet(mut packet: MeshPacket, channel_name: &str, key: &ChannelKey) -> Vec<u8> {
    if let Some(PayloadVariant::Decoded(data)) = &packet.payload_variant {
        let mut plaintext = Vec::new();
        data.encode(&mut plaintext).expect("Data encode should not fail");
        crypto::crypt_payload(key, packet.from, packet.id, &mut plaintext);

        let psk_bytes: &[u8] = match key {
            ChannelKey::Aes256(k) => k,
            ChannelKey::Aes128(k) => k,
        };
        packet.channel = crypto::channel_hash(channel_name, psk_bytes) as u32;
        packet.payload_variant = Some(PayloadVariant::Encrypted(plaintext));
    }
    let mut out = Vec::new();
    packet.encode(&mut out).expect("MeshPacket encode should not fail");
    out
}
